import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Workflow } from "lucide-react";
import Logo from "@/components/Logo";
import DiagramStudio from "@/components/DiagramStudio";
import { SITE_URL, landingSoftwareJsonLd, howToJsonLd, faqListJsonLd, breadcrumbJsonLd } from "@/lib/seo";

const PATH = "/diagram";
const TITLE = "AI Diagram Generator — Editable Flowcharts, Mind Maps & More | EXdeck";
const DESCRIPTION =
  "Free AI diagram maker. Describe it and get an editable vector diagram — flowchart, timeline, mind map, architecture, ER, network, org chart, decision tree, or sequence. Hand-edit the source, live preview, export SVG, PNG, or Mermaid. Not an image — a real editable diagram.";

const KEYWORDS = [
  "ai diagram generator", "ai flowchart generator", "flowchart maker", "mind map maker",
  "mermaid editor", "online diagram tool", "er diagram generator", "sequence diagram generator",
  "org chart maker", "diagram from text", "text to diagram", "ai diagram maker",
];

export const metadata: Metadata = {
  title: { absolute: TITLE },
  description: DESCRIPTION,
  keywords: KEYWORDS,
  alternates: { canonical: PATH },
  openGraph: { title: TITLE, description: DESCRIPTION, url: `${SITE_URL}${PATH}`, type: "website" },
  twitter: { card: "summary_large_image", title: TITLE, description: DESCRIPTION },
};

const STEPS = [
  { name: "Pick a diagram type", text: "Choose flowchart, timeline, mind map, architecture, ER, network, org chart, decision tree, or sequence — each starts from a clean template." },
  { name: "Describe or edit", text: "Type what you want and let AI draft it, or edit the diagram source directly. The preview updates live." },
  { name: "Export", text: "Download a crisp SVG or PNG, or copy the Mermaid source to keep editing anywhere (it also imports into draw.io)." },
];

const FAQ = [
  { q: "Is this a real diagram or just an image?", a: "A real, editable vector diagram. It's defined by structured Mermaid source you can edit anytime, and it renders to scalable SVG — not a flat picture." },
  { q: "What diagram types are supported?", a: "Flowcharts, timelines, mind maps, architecture diagrams, ER diagrams, network diagrams, org charts, decision trees, and sequence diagrams." },
  { q: "Can AI build the diagram for me?", a: "Yes — describe what you need (e.g. 'user authentication flow with JWT') and the AI writes the diagram, which you can then fine-tune by editing the source." },
  { q: "How do I export it?", a: "Download SVG (vector) or PNG, or copy the Mermaid source. The Mermaid source also imports directly into draw.io and other tools, so you can keep editing elsewhere." },
  { q: "Is it free?", a: "Yes — editing and exporting are free in your browser. AI generation uses your EXdeck credits and needs a free sign-in." },
];

export default function DiagramPage() {
  const jsonLd = [
    landingSoftwareJsonLd("EXdeck AI Diagram Generator", DESCRIPTION, PATH),
    howToJsonLd({ name: "How to make a diagram with AI", description: DESCRIPTION, steps: STEPS }),
    faqListJsonLd(FAQ),
    breadcrumbJsonLd([{ name: "Home", path: "/" }, { name: "AI Diagram Generator", path: PATH }]),
  ];

  return (
    <main className="min-h-screen" style={{ background: "var(--ezd-bg-page)", color: "var(--ezd-fg)" }}>
      {jsonLd.map((obj, i) => (
        <script key={i} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(obj) }} />
      ))}

      <header className="border-b" style={{ borderColor: "var(--ezd-divider)" }}>
        <div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4">
          <Logo size="sm" href="/" />
          <Link href="/app" className="inline-flex items-center gap-1.5 text-[13px] font-medium" style={{ color: "var(--ezd-fg-muted)" }}>Open dashboard <ArrowRight size={13} /></Link>
        </div>
      </header>

      <section className="mx-auto max-w-6xl px-5 pt-10 sm:pt-12">
        <div className="text-center">
          <div className="inline-flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-[0.2em]" style={{ color: "var(--ezd-fg-quiet)" }}><Workflow size={12} /> AI Diagram Generator</div>
          <h1 className="mx-auto mt-3 max-w-2xl text-[30px] font-bold leading-[1.1] tracking-tight sm:text-[40px]" style={{ color: "var(--ezd-fg-strong)" }}>Editable diagrams, generated by AI</h1>
          <p className="mx-auto mt-3 max-w-xl text-[15px] leading-relaxed" style={{ color: "var(--ezd-fg-muted)" }}>
            Flowcharts, mind maps, timelines, ER, sequence and more — describe it or edit the source, preview live, and export SVG, PNG, or Mermaid. A real editable diagram, not an image.
          </p>
        </div>

        <div className="mt-8 rounded-3xl border p-4 sm:p-6" style={{ borderColor: "var(--ezd-divider)", background: "var(--ezd-bg-elev)" }}>
          <DiagramStudio />
        </div>
      </section>

      <section className="mx-auto max-w-4xl px-5 py-16">
        <h2 className="text-center text-[24px] font-bold tracking-tight" style={{ color: "var(--ezd-fg-strong)" }}>How it works</h2>
        <div className="mt-8 grid gap-4 sm:grid-cols-3">
          {STEPS.map((s, i) => (
            <div key={s.name} className="rounded-2xl border p-5" style={{ borderColor: "var(--ezd-divider)", background: "var(--ezd-bg-card)" }}>
              <div className="grid h-8 w-8 place-items-center rounded-lg text-[14px] font-bold" style={{ background: "var(--ezd-fg-strong)", color: "var(--ezd-bg-page)" }}>{i + 1}</div>
              <h3 className="mt-3 text-[15px] font-semibold" style={{ color: "var(--ezd-fg-strong)" }}>{s.name}</h3>
              <p className="mt-1.5 text-[13.5px] leading-relaxed" style={{ color: "var(--ezd-fg-muted)" }}>{s.text}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="mx-auto max-w-3xl px-5 pb-20">
        <h2 className="text-[24px] font-bold tracking-tight" style={{ color: "var(--ezd-fg-strong)" }}>Frequently asked questions</h2>
        <div className="mt-6 divide-y" style={{ borderColor: "var(--ezd-divider)" }}>
          {FAQ.map((f) => (
            <details key={f.q} className="group py-4">
              <summary className="cursor-pointer list-none text-[15px] font-semibold" style={{ color: "var(--ezd-fg-strong)" }}>{f.q}</summary>
              <p className="mt-2 text-[14px] leading-relaxed" style={{ color: "var(--ezd-fg-muted)" }}>{f.a}</p>
            </details>
          ))}
        </div>
      </section>
    </main>
  );
}
