"use client";
import { useEffect, useState } from "react";
import { Sparkles, Wand2 } from "lucide-react";
import { getTheme } from "@/lib/themes";

/**
 * Full-screen "deck is being prepared" overlay.
 *
 * A single hero slide card assembles itself in the center of the stage —
 * paper → accent rail → kicker → title → bullets → a small bar chart →
 * footer — looping forever. Two faint "ghost" cards sit behind it for a
 * sense of depth (a deck being built, not one slide).
 *
 * Responsiveness:
 *   - The card width is `min(90vw, 440px)`, so it never overflows a
 *     phone. Every inner element is sized in `em` against a single
 *     `clamp()` font-size on the card, so the whole slide scales as one
 *     unit from a 320px phone up to desktop. No fixed pixel widths that
 *     can clip on small screens.
 *
 * Performance:
 *   - Only `transform` and `opacity` are animated (compositor-only, no
 *     layout/paint). React renders the tree once per open; CSS does the
 *     rest. Smooth even on low-end devices.
 */

/** ms — total animation cycle length, before it loops. */
const CYCLE_MS = 5200;

const ROTATING_LINES = [
  "Reading your brief…",
  "Outlining the story…",
  "Drafting headlines…",
  "Writing the content…",
  "Laying out the slides…",
  "Building the charts…",
  "Applying your template…",
  "Polishing the details…",
  "Almost there…",
];

export default function GenerateOverlay({
  open,
  error,
  loading,
  onRetry,
}: {
  open: boolean;
  error?: string | null;
  loading?: boolean;
  onRetry?: () => void;
}) {
  const [lineIdx, setLineIdx] = useState(0);

  // Lock body scroll while the overlay is mounted.
  useEffect(() => {
    if (!open) return;
    const prev = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => { document.body.style.overflow = prev; };
  }, [open]);

  // Rotate the status line. Cheap — no per-frame work.
  useEffect(() => {
    if (!open) { setLineIdx(0); return; }
    const id = window.setInterval(() => {
      setLineIdx((i) => (i + 1) % ROTATING_LINES.length);
    }, 1500);
    return () => window.clearInterval(id);
  }, [open]);

  if (!open) return null;

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-label="Generating your deck"
      className="fixed inset-0 z-[300] flex items-center justify-center overflow-hidden"
      style={{
        background:
          "radial-gradient(60% 50% at 50% 28%, var(--ezd-bg-hover), transparent 70%), var(--ezd-bg-page)",
      }}
    >
      <BackdropGrid />

      <div
        className={`relative z-10 flex w-full max-w-3xl flex-col items-center px-5 text-center text-white transition-all duration-500 ${
          error ? "scale-[0.98] opacity-20 blur-md" : "scale-100 opacity-100 blur-0"
        }`}
      >
        {/* Brand pill */}
        <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.04] px-3 py-1 text-[11px] font-medium text-white/80 backdrop-blur">
          <Sparkles size={11} className="text-cyan-300" />
          EXdeck · building your deck
        </div>

        {/* Headline */}
        <h2
          className="mb-2 font-semibold text-white"
          style={{ fontSize: "clamp(24px, 5.5vw, 38px)", lineHeight: 1.05, letterSpacing: "-0.025em" }}
        >
          Building your presentation
        </h2>

        {/* Rotating one-liner */}
        <div className="relative h-5 w-full max-w-xs overflow-hidden text-[13px] text-white/55 sm:max-w-md">
          {ROTATING_LINES.map((ln, i) => (
            <span
              key={i}
              className="absolute inset-0 transition-opacity duration-500 ease-out"
              style={{ opacity: i === lineIdx ? 1 : 0 }}
            >
              {ln}
            </span>
          ))}
        </div>

        {/* Stage — single responsive building card with ghosts behind */}
        <div
          className="flex w-full items-center justify-center"
          style={{ margin: "clamp(28px, 7vw, 56px) 0 clamp(24px, 6vw, 44px)", perspective: 1200 }}
        >
          <div className="relative" style={{ width: "min(90vw, 440px)" }}>
            <GhostCard which="left" />
            <GhostCard which="right" />
            <BuildingSlide />
          </div>
        </div>

        {/* Looping progress bar — pure CSS, GPU accelerated. */}
        <div className="relative mb-3 h-[3px] w-48 overflow-hidden rounded-full bg-white/10 sm:w-60">
          <div
            className="ezd-progress absolute inset-y-0 left-0 origin-left rounded-full"
            style={{ width: "100%", background: "var(--ezd-fg-strong)", boxShadow: "0 0 16px var(--ezd-bg-hover)" }}
          />
        </div>

        {/* AI badge */}
        <div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1 text-[11px] text-white/55">
          <Wand2 size={11} className="text-cyan-300" />
          Generated by AI
        </div>

        <p className="mt-3 text-[10px] text-white/30">Sit tight. Usually about 10 seconds.</p>
      </div>

      {error && (
        <div className="fixed inset-0 z-[350] flex items-center justify-center p-6">
          <div
            className="w-full max-w-md rounded-3xl border border-red-500/30 bg-black/80 p-8 text-center backdrop-blur-xl"
            style={{ boxShadow: "0 20px 80px rgba(255,0,0,.15)" }}
          >
            <div className="mb-4 text-5xl">⚠️</div>
            <h3 className="text-2xl font-semibold text-white">Couldn&rsquo;t generate presentation</h3>
            <p className="mt-3 text-sm text-white/60">Something interrupted the generation process.</p>
            <div className="mt-4 rounded-xl bg-white/5 p-3 text-sm text-red-300">{error}</div>
            <div className="mt-6 flex justify-center gap-3">
              <button
                onClick={onRetry}
                disabled={loading}
                className="rounded-xl bg-white px-5 py-2.5 font-medium text-black transition hover:opacity-90"
              >
                ↻ Try Again
              </button>
              <button
                onClick={() => window.location.reload()}
                className="rounded-xl border border-white/15 px-5 py-2.5 text-white/70 transition hover:bg-white/5"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}

      {/* All animation timing lives here. transform + opacity only. */}
      <style jsx global>{`
        /* Phase budget (% of cycle):
              0-3    rest
              3-13   paper rises in
              13-22  accent rail grows
              22-30  kicker
              30-44  title
              44-66  bullets (staggered)
              50-74  chart bars grow (staggered)
              74-82  footer
              82-100 hold */

        @keyframes ezd-paper {
          0%, 3%    { opacity: 0; transform: translateY(16px) scale(0.96); }
          13%, 100% { opacity: 1; transform: translateY(0)    scale(1); }
        }
        @keyframes ezd-rail {
          0%, 13%   { transform: scaleX(0); }
          22%, 100% { transform: scaleX(1); }
        }
        @keyframes ezd-kicker {
          0%, 22%   { opacity: 0; transform: translateY(4px); }
          30%, 100% { opacity: 1; transform: translateY(0); }
        }
        @keyframes ezd-title {
          0%, 30%   { opacity: 0; transform: translateY(7px); }
          44%, 100% { opacity: 1; transform: translateY(0); }
        }
        @keyframes ezd-b1 {
          0%, 44%   { opacity: 0; transform: translateX(-6px); }
          54%, 100% { opacity: 1; transform: translateX(0); }
        }
        @keyframes ezd-b2 {
          0%, 50%   { opacity: 0; transform: translateX(-6px); }
          60%, 100% { opacity: 1; transform: translateX(0); }
        }
        @keyframes ezd-b3 {
          0%, 56%   { opacity: 0; transform: translateX(-6px); }
          66%, 100% { opacity: 1; transform: translateX(0); }
        }
        @keyframes ezd-bar1 {
          0%, 50%   { transform: scaleY(0); }
          60%, 100% { transform: scaleY(1); }
        }
        @keyframes ezd-bar2 {
          0%, 56%   { transform: scaleY(0); }
          66%, 100% { transform: scaleY(1); }
        }
        @keyframes ezd-bar3 {
          0%, 62%   { transform: scaleY(0); }
          72%, 100% { transform: scaleY(1); }
        }
        @keyframes ezd-bar4 {
          0%, 68%   { transform: scaleY(0); }
          78%, 100% { transform: scaleY(1); }
        }
        @keyframes ezd-foot {
          0%, 74%   { opacity: 0; }
          82%, 100% { opacity: 1; }
        }
        @keyframes ezd-progress {
          0%   { transform: scaleX(0); }
          92%  { transform: scaleX(1); }
          100% { transform: scaleX(1); }
        }
        @keyframes ezd-float-a {
          0%, 100% { transform: rotate(-7deg) translate(-12%, 4%) scale(0.9); }
          50%      { transform: rotate(-8deg) translate(-12%, 1%) scale(0.9); }
        }
        @keyframes ezd-float-b {
          0%, 100% { transform: rotate(7deg) translate(12%, 4%) scale(0.9); }
          50%      { transform: rotate(8deg) translate(12%, 7%) scale(0.9); }
        }

        .ezd-paper  { animation: ezd-paper  ${CYCLE_MS}ms cubic-bezier(.2,.7,.2,1) infinite both; transform-origin: bottom; will-change: transform, opacity; }
        .ezd-rail   { animation: ezd-rail   ${CYCLE_MS}ms cubic-bezier(.2,.7,.2,1) infinite both; transform-origin: left; }
        .ezd-kicker { animation: ezd-kicker ${CYCLE_MS}ms cubic-bezier(.2,.7,.2,1) infinite both; }
        .ezd-title  { animation: ezd-title  ${CYCLE_MS}ms cubic-bezier(.2,.7,.2,1) infinite both; }
        .ezd-b1     { animation: ezd-b1     ${CYCLE_MS}ms cubic-bezier(.2,.7,.2,1) infinite both; }
        .ezd-b2     { animation: ezd-b2     ${CYCLE_MS}ms cubic-bezier(.2,.7,.2,1) infinite both; }
        .ezd-b3     { animation: ezd-b3     ${CYCLE_MS}ms cubic-bezier(.2,.7,.2,1) infinite both; }
        .ezd-bar1   { animation: ezd-bar1   ${CYCLE_MS}ms cubic-bezier(.2,.7,.2,1) infinite both; transform-origin: bottom; }
        .ezd-bar2   { animation: ezd-bar2   ${CYCLE_MS}ms cubic-bezier(.2,.7,.2,1) infinite both; transform-origin: bottom; }
        .ezd-bar3   { animation: ezd-bar3   ${CYCLE_MS}ms cubic-bezier(.2,.7,.2,1) infinite both; transform-origin: bottom; }
        .ezd-bar4   { animation: ezd-bar4   ${CYCLE_MS}ms cubic-bezier(.2,.7,.2,1) infinite both; transform-origin: bottom; }
        .ezd-foot   { animation: ezd-foot   ${CYCLE_MS}ms cubic-bezier(.2,.7,.2,1) infinite both; }
        .ezd-progress { animation: ezd-progress ${CYCLE_MS}ms cubic-bezier(.45,.05,.55,.95) infinite both; transform-origin: left; }
        .ezd-ghost-a { animation: ezd-float-a 6s ease-in-out infinite; }
        .ezd-ghost-b { animation: ezd-float-b 6s ease-in-out infinite; }

        @media (prefers-reduced-motion: reduce) {
          .ezd-paper, .ezd-rail, .ezd-kicker, .ezd-title,
          .ezd-b1, .ezd-b2, .ezd-b3,
          .ezd-bar1, .ezd-bar2, .ezd-bar3, .ezd-bar4,
          .ezd-foot, .ezd-ghost-a, .ezd-ghost-b, .ezd-progress {
            animation: none !important; opacity: 1; transform: none;
          }
        }
      `}</style>
    </div>
  );
}

/* ------------------------------------------------------------------ *
 *                       The building hero slide                        *
 * ------------------------------------------------------------------ */

const BARS = [
  { h: "45%", cls: "ezd-bar1" },
  { h: "72%", cls: "ezd-bar2" },
  { h: "58%", cls: "ezd-bar3" },
  { h: "100%", cls: "ezd-bar4" },
];

function BuildingSlide() {
  const theme = getTheme("cobalt") || getTheme("midnight");
  if (!theme) return null;

  return (
    <div className="relative z-10" style={{ width: "100%" }}>
      <div
        className="ezd-paper relative overflow-hidden rounded-xl border shadow-[0_40px_80px_-30px_rgba(0,0,0,0.75)]"
        style={{
          aspectRatio: "16 / 9",
          background: theme.bg,
          color: theme.fg,
          borderColor: "var(--ezd-divider)",
          // One clamp drives the whole slide; all inner sizes are in em.
          fontSize: "clamp(8px, calc(3px + 2vw), 14px)",
          fontFamily: "ui-sans-serif, system-ui, -apple-system, sans-serif",
        }}
      >
        {/* Accent rail along the top */}
        <div className="ezd-rail absolute left-0 top-0 h-[0.22em] w-full" style={{ background: theme.accent }} />

        <div style={{ display: "flex", flexDirection: "column", height: "100%", padding: "1.5em 1.6em" }}>
          {/* Kicker */}
          <div
            className="ezd-kicker"
            style={{ color: theme.accent, fontSize: "0.62em", fontWeight: 700, letterSpacing: "0.24em" }}
          >
            Q1 OVERVIEW
          </div>

          {/* Title */}
          <div
            className="ezd-title"
            style={{ marginTop: "0.55em", color: theme.fg, fontSize: "1.6em", fontWeight: 600, lineHeight: 1.12, letterSpacing: "-0.015em" }}
          >
            What changed
            <br />
            this quarter
          </div>

          {/* Body: bullets + mini chart */}
          <div style={{ marginTop: "auto", display: "grid", gridTemplateColumns: "1.05fr 0.95fr", gap: "1.2em", alignItems: "end" }}>
            {/* Bullets */}
            <div style={{ display: "flex", flexDirection: "column", gap: "0.62em" }}>
              {[
                { cls: "ezd-b1", t: "Net retention hit 124%" },
                { cls: "ezd-b2", t: "Three enterprise logos" },
                { cls: "ezd-b3", t: "Two senior eng hires" },
              ].map((b) => (
                <div key={b.cls} className={b.cls} style={{ display: "flex", alignItems: "flex-start", gap: "0.5em", fontSize: "0.74em", lineHeight: 1.3 }}>
                  <span style={{ color: theme.accent, fontWeight: 700 }}>—</span>
                  <span style={{ opacity: 0.92 }}>{b.t}</span>
                </div>
              ))}
            </div>

            {/* Mini bar chart */}
            <div style={{ display: "flex", alignItems: "flex-end", justifyContent: "space-between", gap: "0.45em", height: "4.4em" }}>
              {BARS.map((bar, i) => (
                <div key={i} style={{ flex: 1, height: "100%", display: "flex", alignItems: "flex-end" }}>
                  <div
                    className={bar.cls}
                    style={{
                      width: "100%",
                      height: bar.h,
                      borderRadius: "0.2em 0.2em 0 0",
                      background: i === BARS.length - 1 ? theme.accent : `${theme.accent}`,
                      opacity: i === BARS.length - 1 ? 1 : 0.5,
                    }}
                  />
                </div>
              ))}
            </div>
          </div>

          {/* Footer */}
          <div className="ezd-foot" style={{ marginTop: "1.1em" }}>
            <div className="h-px w-full" style={{ background: theme.fg, opacity: 0.16 }} />
            <div
              style={{ marginTop: "0.5em", display: "flex", alignItems: "center", justifyContent: "space-between", fontSize: "0.58em", fontWeight: 700, letterSpacing: "0.22em", color: theme.muted }}
            >
              <span>ACME · Q1 2026</span>
              <span>04 / 12</span>
            </div>
          </div>
        </div>
      </div>

      {/* Soft glow under the card */}
      <div
        aria-hidden
        className="pointer-events-none absolute inset-x-6 -bottom-3 h-8 rounded-full blur-2xl"
        style={{ background: "rgba(120,120,160,0.30)" }}
      />
    </div>
  );
}

/* ------------------------------------------------------------------ *
 *                  Ghost cards behind the hero slide                   *
 * ------------------------------------------------------------------ */

function GhostCard({ which }: { which: "left" | "right" }) {
  const theme = getTheme(which === "left" ? "emerald" : "crimson") || getTheme("cobalt");
  if (!theme) return null;
  return (
    <div
      aria-hidden
      className={`absolute inset-0 ${which === "left" ? "ezd-ghost-a" : "ezd-ghost-b"}`}
      style={{ opacity: 0.5 }}
    >
      <div
        className="relative h-full w-full overflow-hidden rounded-xl border shadow-[0_30px_60px_-30px_rgba(0,0,0,0.6)]"
        style={{ aspectRatio: "16 / 9", background: theme.bg, borderColor: "var(--ezd-divider)" }}
      >
        <div className="absolute left-0 top-0 h-[0.22em] w-full" style={{ background: theme.accent }} />
        {/* skeleton lines */}
        <div style={{ position: "absolute", left: "9%", top: "26%", width: "42%", height: "0.5em", borderRadius: 99, background: theme.fg, opacity: 0.22 }} />
        <div style={{ position: "absolute", left: "9%", top: "40%", width: "60%", height: "0.5em", borderRadius: 99, background: theme.fg, opacity: 0.14 }} />
        <div style={{ position: "absolute", left: "9%", bottom: "16%", width: "30%", height: "0.45em", borderRadius: 99, background: theme.accent, opacity: 0.5 }} />
      </div>
    </div>
  );
}

/* ------------------------------------------------------------------ *
 *                              Backdrop                                 *
 * ------------------------------------------------------------------ */

function BackdropGrid() {
  return (
    <div
      aria-hidden
      className="pointer-events-none absolute inset-0"
      style={{
        backgroundImage:
          "linear-gradient(var(--ezd-divider) 1px, transparent 1px), linear-gradient(90deg, var(--ezd-divider) 1px, transparent 1px)",
        backgroundSize: "64px 64px",
        maskImage: "radial-gradient(ellipse at 50% 35%, black 0%, black 35%, transparent 80%)",
        WebkitMaskImage: "radial-gradient(ellipse at 50% 35%, black 0%, black 35%, transparent 80%)",
        opacity: 0.4,
      }}
    />
  );
}
