"use client";
import { useEffect, useState } from "react";
import { Sparkles, Wand2 } from "lucide-react";

/**
 * Full-screen "deck is being prepared" overlay shown while we wait for the
 * generation API to come back. Plays a building-slides animation. Stays on
 * screen for at least 10s so a fast generation still feels deliberate;
 * longer generations keep animating until the parent unmounts the overlay.
 */

export default function GenerateOverlay({ open }: { open: boolean }) {
  const [tick, setTick] = useState(0);

  // Lock body scroll while the overlay is mounted so the page underneath
  // can't scroll behind it on long pages or jittery touch devices.
  useEffect(() => {
    if (!open) return;
    const prev = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => { document.body.style.overflow = prev; };
  }, [open]);

  // 30-fps tick used to animate the small slide previews.
  useEffect(() => {
    if (!open) return;
    let raf = 0;
    let last = performance.now();
    const loop = (now: number) => {
      if (now - last > 33) {
        setTick((t) => t + 1);
        last = now;
      }
      raf = requestAnimationFrame(loop);
    };
    raf = requestAnimationFrame(loop);
    return () => cancelAnimationFrame(raf);
  }, [open]);

  if (!open) return null;

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-label="Generating your deck"
      className="fixed inset-0 z-[300] flex items-center justify-center"
      style={{
        background:
          "radial-gradient(60% 50% at 50% 30%, rgba(124,92,255,0.25), transparent 70%), radial-gradient(40% 35% at 80% 80%, rgba(34,197,94,0.12), transparent 70%), #050507",
      }}
    >
      <Orbs />

      <div className="relative z-10 flex w-full max-w-3xl flex-col items-center px-6 text-center text-white">
        <div className="mb-5 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs text-white/75">
          <Sparkles size={11} className="text-violet-300" />
          DeckFlow
        </div>

        <h2 className="mb-2 text-3xl font-semibold tracking-tight md:text-4xl">
          Building your deck
          <Dots />
        </h2>
        <p className="text-sm text-white/55">
          Sit tight. This usually takes about ten seconds.
        </p>

        <div className="my-12 flex h-44 items-end gap-3">
          {Array.from({ length: 5 }).map((_, i) => (
            <MiniSlide key={i} index={i} tick={tick} />
          ))}
        </div>

        <div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1 text-[11px] text-white/55">
          <Wand2 size={11} className="text-violet-300" />
          Generated by AI · open-weight model
        </div>
      </div>
    </div>
  );
}

function MiniSlide({ index, tick }: { index: number; tick: number }) {
  const period = 90;
  const offset = index * 18;
  const phase = ((tick + offset) % period) / period;
  const wave = 0.5 - 0.5 * Math.cos(phase * Math.PI * 2);
  const height = 70 + wave * 80;
  const colors = ["#a78bfa", "#f472b6", "#34d399", "#facc15", "#60a5fa"];
  const c = colors[index % colors.length];

  return (
    <div
      className="relative w-20 overflow-hidden rounded-lg border border-white/10 bg-white/5 backdrop-blur-sm"
      style={{
        height,
        transition: "height 80ms linear",
        boxShadow: `0 6px 24px -10px ${c}90`,
      }}
    >
      <div
        style={{
          position: "absolute", left: 0, top: 0, height: 5, width: "100%",
          background: c,
        }}
      />
      <div style={{ padding: 8 }}>
        <div style={{ height: 5, width: "70%", background: "rgba(255,255,255,0.6)", borderRadius: 2 }} />
        <div style={{ height: 3, width: "50%", marginTop: 5, background: "rgba(255,255,255,0.3)", borderRadius: 2 }} />
        <div style={{ height: 3, width: "60%", marginTop: 4, background: "rgba(255,255,255,0.3)", borderRadius: 2 }} />
        <div style={{ height: 3, width: "40%", marginTop: 4, background: "rgba(255,255,255,0.3)", borderRadius: 2 }} />
      </div>
    </div>
  );
}

function Dots() {
  return (
    <span className="ml-1 inline-block">
      <span className="dot dot-1">.</span>
      <span className="dot dot-2">.</span>
      <span className="dot dot-3">.</span>
      <style jsx>{`
        .dot { animation: gen-dot 1.2s infinite; opacity: 0.3; }
        .dot-2 { animation-delay: 0.2s; }
        .dot-3 { animation-delay: 0.4s; }
        @keyframes gen-dot {
          0%, 20% { opacity: 0.3; }
          50% { opacity: 1; }
          100% { opacity: 0.3; }
        }
      `}</style>
    </span>
  );
}

function Orbs() {
  return (
    <>
      <div className="orb orb-a" />
      <div className="orb orb-b" />
      <div className="orb orb-c" />
      <style jsx>{`
        .orb {
          position: absolute;
          border-radius: 9999px;
          filter: blur(60px);
          opacity: 0.55;
          animation: float 14s ease-in-out infinite;
        }
        .orb-a {
          top: -120px; left: -120px; width: 380px; height: 380px;
          background: radial-gradient(circle, #7C5CFF, transparent 70%);
        }
        .orb-b {
          bottom: -120px; right: -120px; width: 460px; height: 460px;
          background: radial-gradient(circle, #f472b6, transparent 70%);
          animation-delay: -4s;
        }
        .orb-c {
          top: 30%; right: 15%; width: 260px; height: 260px;
          background: radial-gradient(circle, #34d399, transparent 70%);
          animation-delay: -8s;
        }
        @keyframes float {
          0%   { transform: translate(0, 0) scale(1); }
          50%  { transform: translate(30px, -20px) scale(1.08); }
          100% { transform: translate(0, 0) scale(1); }
        }
      `}</style>
    </>
  );
}
