/**
 * Deck templates: curated combinations of theme + font + graphic + per-layout
 * variants + a sample prompt. Picking a template skips the theme/font/graphic
 * steps and jumps straight to "edit prompt and generate".
 *
 * Variant defaults are applied to every slide in the generated deck so the
 * whole deck inherits a cohesive visual language (e.g. "Editorial Sand" makes
 * every quote slide use the editorial pull-quote variant, every title-hero
 * use the underlined variant, etc.).
 */

import type { ContentDensity, Slide } from "./types";

export type TemplateVariantDefaults = {
  titleVariant?: Slide["titleVariant"];
  bulletsVariant?: Slide["bulletsVariant"];
  twoColumnVariant?: Slide["twoColumnVariant"];
  tableVariant?: Slide["tableVariant"];
  quoteVariant?: Slide["quoteVariant"];
  sectionVariant?: Slide["sectionVariant"];
  closingVariant?: Slide["closingVariant"];
};

export type DeckTemplate = {
  id: string;
  name: string;
  /** One-line description shown under the title. */
  tagline: string;
  /** Short label used as a chip (Pitch, Lecture, Report, etc.). */
  category: string;
  themeId: string;
  fontId: string;
  graphicId: string;
  /** Optional accent override for the graphic. */
  graphicAccent?: string;
  /** Generation defaults. */
  density?: ContentDensity;
  includeReferences?: boolean;
  /** Sample prompt seeded into the brief so the user can tweak it. */
  samplePrompt: string;
  /** Per-layout visual variants applied to every slide after generation. */
  variants: TemplateVariantDefaults;
};

export const DECK_TEMPLATES: DeckTemplate[] = [
  {
    id: "bold-cobalt",
    name: "Bold Cobalt",
    tagline: "Solid color, big confident type. Made for keynote-style decks.",
    category: "Keynote",
    themeId: "cobalt",
    fontId: "outfit",
    graphicId: "corner-blocks",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Company all-hands keynote covering Q3 results, the product bet for next year, and how the team is growing.",
    variants: {
      titleVariant: "underlined",
      bulletsVariant: "numbered",
      twoColumnVariant: "numbered",
      tableVariant: "accent-header",
      quoteVariant: "centered",
      sectionVariant: "split",
      closingVariant: "cta",
    },
  },
  {
    id: "crimson-hero",
    name: "Crimson Hero",
    tagline: "Dramatic red panels with editorial pacing.",
    category: "Pitch",
    themeId: "crimson",
    fontId: "bricolage",
    graphicId: "arch-corner",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Seed-stage pitch for a consumer app. Problem, insight, product, traction, the team, the ask.",
    variants: {
      titleVariant: "numbered",
      bulletsVariant: "icon-check",
      twoColumnVariant: "compare",
      tableVariant: "accent-header",
      quoteVariant: "editorial",
      sectionVariant: "kicker-hero",
      closingVariant: "cta",
    },
  },
  {
    id: "editorial-sand",
    name: "Editorial Sand",
    tagline: "Magazine feel. Serif type, generous whitespace, quiet decoration.",
    category: "Editorial",
    themeId: "sand",
    fontId: "playfair",
    graphicId: "minimal-divider",
    density: "detailed",
    includeReferences: true,
    samplePrompt: "Long-form report on the future of remote work, written for a thoughtful business audience.",
    variants: {
      titleVariant: "underlined",
      bulletsVariant: "dashed",
      twoColumnVariant: "divider",
      tableVariant: "minimal",
      quoteVariant: "editorial",
      sectionVariant: "minimal",
      closingVariant: "signature",
    },
  },
  {
    id: "tech-mono",
    name: "Tech Mono",
    tagline: "Mono type, blueprint grid. Engineering and product reviews.",
    category: "Engineering",
    themeId: "charcoal",
    fontId: "jetbrains",
    graphicId: "blueprint",
    density: "detailed",
    includeReferences: false,
    samplePrompt: "Engineering review of a payments service: architecture, SLOs, on-call pain, and what we ship next quarter.",
    variants: {
      titleVariant: "centered",
      bulletsVariant: "dashed",
      twoColumnVariant: "classic",
      tableVariant: "compact",
      quoteVariant: "card",
      sectionVariant: "minimal",
      closingVariant: "centered",
    },
  },
  {
    id: "royal-indigo",
    name: "Royal Indigo",
    tagline: "Saturated indigo with gold accents. Big-stage confidence.",
    category: "Keynote",
    themeId: "royal-indigo",
    fontId: "space-grotesk",
    graphicId: "corner-arc",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Industry keynote on AI-native developer tools. Where we are, where it's going, what to build now.",
    variants: {
      titleVariant: "big-initial",
      bulletsVariant: "cards",
      twoColumnVariant: "cards",
      tableVariant: "accent-header",
      quoteVariant: "stacked",
      sectionVariant: "split",
      closingVariant: "cta",
    },
  },
  {
    id: "investor-navy",
    name: "Investor Navy",
    tagline: "Boardroom safe. Disciplined columns and clean tables.",
    category: "Investor",
    themeId: "corp-navy",
    fontId: "inter",
    graphicId: "side-bar",
    density: "detailed",
    includeReferences: false,
    samplePrompt: "Q1 investor update covering ARR growth, churn, hiring, and our ask for the next round.",
    variants: {
      titleVariant: "asymmetric",
      bulletsVariant: "numbered",
      twoColumnVariant: "numbered",
      tableVariant: "accent-header",
      quoteVariant: "card",
      sectionVariant: "split",
      closingVariant: "contact",
    },
  },
  {
    id: "mint-startup",
    name: "Mint Startup",
    tagline: "Friendly and modern. Soft mint with confident type.",
    category: "Startup",
    themeId: "mint-sage",
    fontId: "dm-sans",
    graphicId: "dot-field",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "B2B SaaS pitch for an expense automation tool. Problem, solution, traction, market, ask.",
    variants: {
      titleVariant: "big-initial",
      bulletsVariant: "cards",
      twoColumnVariant: "cards",
      tableVariant: "minimal",
      quoteVariant: "card",
      sectionVariant: "kicker-hero",
      closingVariant: "cta",
    },
  },
  {
    id: "burgundy-edit",
    name: "Burgundy Editorial",
    tagline: "Wine-and-cream serif feel. Best for deep narrative pieces.",
    category: "Editorial",
    themeId: "burgundy",
    fontId: "fraunces",
    graphicId: "ribbon-stripe",
    density: "detailed",
    includeReferences: true,
    samplePrompt: "A reflective talk on craftsmanship in software, written for a senior engineering audience.",
    variants: {
      titleVariant: "numbered",
      bulletsVariant: "dashed",
      twoColumnVariant: "divider",
      tableVariant: "minimal",
      quoteVariant: "editorial",
      sectionVariant: "chapter",
      closingVariant: "signature",
    },
  },
  {
    id: "plum-bold",
    name: "Plum Bold",
    tagline: "Punchy purple, big numbers. Brand-forward decks.",
    category: "Brand",
    themeId: "plum",
    fontId: "syne",
    graphicId: "concentric",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Brand vision deck for a creative agency. Who we are, what we believe, work we love, who we want to work with.",
    variants: {
      titleVariant: "big-initial",
      bulletsVariant: "numbered",
      twoColumnVariant: "cards",
      tableVariant: "accent-header",
      quoteVariant: "stacked",
      sectionVariant: "kicker-hero",
      closingVariant: "qa",
    },
  },
  {
    id: "forest-academic",
    name: "Forest Academic",
    tagline: "Quiet forest tones, classical serif. Lectures and research.",
    category: "Lecture",
    themeId: "forest-cream",
    fontId: "lora",
    graphicId: "topographic",
    density: "comprehensive",
    includeReferences: true,
    samplePrompt: "Undergraduate lecture on transformer architectures: attention, encoders, decoders, and a worked example.",
    variants: {
      titleVariant: "centered",
      bulletsVariant: "icon-check",
      twoColumnVariant: "classic",
      tableVariant: "minimal",
      quoteVariant: "card",
      sectionVariant: "chapter",
      closingVariant: "centered",
    },
  },
  {
    id: "tangerine-bold",
    name: "Tangerine Bold",
    tagline: "Solid tangerine. Marketing and creative kickoffs.",
    category: "Marketing",
    themeId: "tangerine",
    fontId: "archivo",
    graphicId: "corner-circles",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Marketing campaign brief for a Q4 holiday push. Audience, message, channels, KPIs, timeline.",
    variants: {
      titleVariant: "asymmetric",
      bulletsVariant: "cards",
      twoColumnVariant: "cards",
      tableVariant: "accent-header",
      quoteVariant: "card",
      sectionVariant: "split",
      closingVariant: "cta",
    },
  },
  {
    id: "slate-bold",
    name: "Slate Bold",
    tagline: "Slate gray with amber accents. Strategy and ops decks.",
    category: "Strategy",
    themeId: "slate-bold",
    fontId: "plus-jakarta",
    graphicId: "editorial-grid",
    density: "detailed",
    includeReferences: false,
    samplePrompt: "Annual strategy review: where we won, where we lost, the bets we are doubling down on next year.",
    variants: {
      titleVariant: "underlined",
      bulletsVariant: "numbered",
      twoColumnVariant: "compare",
      tableVariant: "accent-header",
      quoteVariant: "editorial",
      sectionVariant: "minimal",
      closingVariant: "signature",
    },
  },

  /* ----- additional templates: more variety, more vibes ----- */
  {
    id: "ivory-classic",
    name: "Ivory Classic",
    tagline: "Black serif on warm ivory. Quietly authoritative.",
    category: "Editorial",
    themeId: "ivory",
    fontId: "playfair",
    graphicId: "minimal-divider",
    density: "detailed",
    includeReferences: true,
    samplePrompt: "An essay on the state of typography in 2026: where it is, where it's going, who's pushing it.",
    variants: {
      titleVariant: "underlined", bulletsVariant: "dashed", twoColumnVariant: "divider",
      tableVariant: "minimal", quoteVariant: "editorial", sectionVariant: "minimal",
      closingVariant: "signature",
    },
  },
  {
    id: "ocean-pearl",
    name: "Ocean & Pearl",
    tagline: "Deep teal accents on pearl. Calm, professional, marine.",
    category: "Investor",
    themeId: "ocean-deep",
    fontId: "ibm-plex-sans",
    graphicId: "wave",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Series B raise deck for a logistics platform. Customers, growth, unit economics, the ask.",
    variants: {
      titleVariant: "asymmetric", bulletsVariant: "numbered", twoColumnVariant: "numbered",
      tableVariant: "bordered", quoteVariant: "card", sectionVariant: "split",
      closingVariant: "contact",
    },
  },
  {
    id: "rose-gold",
    name: "Rose Gold",
    tagline: "Warm copper on cream. Beauty, fashion, lifestyle brands.",
    category: "Brand",
    themeId: "rose-gold",
    fontId: "fraunces",
    graphicId: "arch-corner",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Brand book for a skincare startup. Vision, voice, principles, do's and don'ts.",
    variants: {
      titleVariant: "centered", bulletsVariant: "dashed", twoColumnVariant: "cards",
      tableVariant: "minimal", quoteVariant: "editorial", sectionVariant: "kicker-hero",
      closingVariant: "signature",
    },
  },
  {
    id: "emerald-power",
    name: "Emerald Power",
    tagline: "Saturated emerald with gold. Sustainability, climate, ESG.",
    category: "Keynote",
    themeId: "emerald",
    fontId: "manrope",
    graphicId: "topographic",
    density: "balanced",
    includeReferences: true,
    samplePrompt: "Climate strategy keynote: where we are on emissions, the targets, the path, the partners.",
    variants: {
      titleVariant: "big-initial", bulletsVariant: "icon-check", twoColumnVariant: "compare",
      tableVariant: "accent-header", quoteVariant: "stacked", sectionVariant: "split",
      closingVariant: "cta",
    },
  },
  {
    id: "powder-rose",
    name: "Powder Rose",
    tagline: "Soft rose with rich crimson accents. Feminine, modern, friendly.",
    category: "Brand",
    themeId: "powder-rose",
    fontId: "outfit",
    graphicId: "corner-circles",
    density: "concise",
    includeReferences: false,
    samplePrompt: "Launch deck for a wellness app aimed at busy professionals. The why, the how, the first 90 days.",
    variants: {
      titleVariant: "centered", bulletsVariant: "cards", twoColumnVariant: "cards",
      tableVariant: "minimal", quoteVariant: "card", sectionVariant: "kicker-hero",
      closingVariant: "qa",
    },
  },
  {
    id: "lavender-dream",
    name: "Lavender Dream",
    tagline: "Soft lavender with deep purple. Creative ops and design reviews.",
    category: "Brand",
    themeId: "lavender",
    fontId: "bricolage",
    graphicId: "mesh-gradient",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Design review for the new mobile onboarding flow. Goals, the journey, what tested well, what didn't.",
    variants: {
      titleVariant: "big-initial", bulletsVariant: "cards", twoColumnVariant: "cards",
      tableVariant: "minimal", quoteVariant: "card", sectionVariant: "kicker-hero",
      closingVariant: "qa",
    },
  },
  {
    id: "soft-indigo",
    name: "Soft Indigo",
    tagline: "Calm indigo wash. Onboarding decks and internal training.",
    category: "Training",
    themeId: "soft-indigo",
    fontId: "figtree",
    graphicId: "soft-grid",
    density: "comprehensive",
    includeReferences: false,
    samplePrompt: "Onboarding deck for new engineers. Tools, process, code review culture, who to ask for what.",
    variants: {
      titleVariant: "underlined", bulletsVariant: "icon-check", twoColumnVariant: "classic",
      tableVariant: "zebra", quoteVariant: "centered", sectionVariant: "minimal",
      closingVariant: "centered",
    },
  },
  {
    id: "halftone-print",
    name: "Halftone Print",
    tagline: "Newsprint halftone, editorial type. Magazine-style features.",
    category: "Editorial",
    themeId: "ivory",
    fontId: "merriweather",
    graphicId: "halftone",
    density: "detailed",
    includeReferences: true,
    samplePrompt: "Long-read essay on the rebirth of print magazines in a digital era.",
    variants: {
      titleVariant: "numbered", bulletsVariant: "dashed", twoColumnVariant: "divider",
      tableVariant: "minimal", quoteVariant: "editorial", sectionVariant: "chapter",
      closingVariant: "signature",
    },
  },
  {
    id: "memphis-pop",
    name: "Memphis Pop",
    tagline: "Squiggles, dots, shapes. Playful, design-forward, attention-grabbing.",
    category: "Brand",
    themeId: "blue-white",
    fontId: "syne",
    graphicId: "memphis",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Pitch for a youth-oriented streaming platform. Vibes, audience, content strategy, the launch.",
    variants: {
      titleVariant: "big-initial", bulletsVariant: "cards", twoColumnVariant: "cards",
      tableVariant: "accent-header", quoteVariant: "stacked", sectionVariant: "kicker-hero",
      closingVariant: "cta",
    },
  },
  {
    id: "bauhaus",
    name: "Bauhaus",
    tagline: "Geometric shapes, primary palette. Architecture and design firms.",
    category: "Brand",
    themeId: "ivory",
    fontId: "archivo",
    graphicId: "bauhaus",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Studio overview for an architecture firm. Philosophy, recent work, the team, what we are looking for.",
    variants: {
      titleVariant: "asymmetric", bulletsVariant: "numbered", twoColumnVariant: "cards",
      tableVariant: "bordered", quoteVariant: "card", sectionVariant: "split",
      closingVariant: "contact",
    },
  },
  {
    id: "blueprint-eng",
    name: "Blueprint",
    tagline: "Drafting grid, technical type. Engineering RFCs and ADR walkthroughs.",
    category: "Engineering",
    themeId: "blue-white",
    fontId: "ibm-plex-sans",
    graphicId: "blueprint",
    density: "comprehensive",
    includeReferences: false,
    samplePrompt: "RFC review for migrating from Postgres to a sharded setup. Why, the design, tradeoffs, rollout.",
    variants: {
      titleVariant: "underlined", bulletsVariant: "dashed", twoColumnVariant: "compare",
      tableVariant: "compact", quoteVariant: "card", sectionVariant: "minimal",
      closingVariant: "centered",
    },
  },
  {
    id: "dot-field",
    name: "Dot Field",
    tagline: "Atmospheric dots, soft fade. Data and AI products.",
    category: "Engineering",
    themeId: "fog",
    fontId: "space-grotesk",
    graphicId: "dot-field",
    density: "detailed",
    includeReferences: true,
    samplePrompt: "Technical deep-dive on our recommendation system: data, model, experiments, the next bet.",
    variants: {
      titleVariant: "centered", bulletsVariant: "dashed", twoColumnVariant: "classic",
      tableVariant: "minimal", quoteVariant: "card", sectionVariant: "minimal",
      closingVariant: "qa",
    },
  },
  {
    id: "concentric",
    name: "Concentric",
    tagline: "Quiet arcs in the corner. Boardroom-clean strategy decks.",
    category: "Strategy",
    themeId: "blue-white",
    fontId: "inter",
    graphicId: "concentric",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Three-year operating plan. Where we are, the bets, the milestones, what could go wrong.",
    variants: {
      titleVariant: "asymmetric", bulletsVariant: "numbered", twoColumnVariant: "numbered",
      tableVariant: "accent-header", quoteVariant: "card", sectionVariant: "split",
      closingVariant: "contact",
    },
  },
  {
    id: "stripes-corp",
    name: "Diagonal Stripes",
    tagline: "Energetic diagonals, corporate restraint. Sales kickoffs.",
    category: "Sales",
    themeId: "red-white",
    fontId: "manrope",
    graphicId: "diagonal-stripes",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Sales kickoff for the new fiscal year. Targets, territories, plays, incentives.",
    variants: {
      titleVariant: "underlined", bulletsVariant: "numbered", twoColumnVariant: "compare",
      tableVariant: "accent-header", quoteVariant: "stacked", sectionVariant: "split",
      closingVariant: "cta",
    },
  },
  {
    id: "olive-academic",
    name: "Olive Academic",
    tagline: "Olive serif. Scholarly conferences and dissertations.",
    category: "Lecture",
    themeId: "olive",
    fontId: "source-serif",
    graphicId: "topographic",
    density: "comprehensive",
    includeReferences: true,
    samplePrompt: "Conference paper presentation: hypothesis, methodology, findings, limitations, future work.",
    variants: {
      titleVariant: "centered", bulletsVariant: "dashed", twoColumnVariant: "classic",
      tableVariant: "minimal", quoteVariant: "card", sectionVariant: "chapter",
      closingVariant: "qa",
    },
  },
  {
    id: "sky-startup",
    name: "Sky Startup",
    tagline: "Open sky blues. Optimistic startup demos.",
    category: "Startup",
    themeId: "sky",
    fontId: "dm-sans",
    graphicId: "wave",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Demo day pitch for a developer tool that auto-generates database migrations.",
    variants: {
      titleVariant: "big-initial", bulletsVariant: "cards", twoColumnVariant: "cards",
      tableVariant: "accent-header", quoteVariant: "card", sectionVariant: "kicker-hero",
      closingVariant: "cta",
    },
  },
  {
    id: "mosaic-creative",
    name: "Mosaic",
    tagline: "Colorful triangle mosaic. Workshop decks, creative kickoffs.",
    category: "Marketing",
    themeId: "purple-white",
    fontId: "outfit",
    graphicId: "mosaic",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Brand workshop kickoff. Discovery, ideation, sprints, deliverables, timeline.",
    variants: {
      titleVariant: "asymmetric", bulletsVariant: "cards", twoColumnVariant: "cards",
      tableVariant: "accent-header", quoteVariant: "card", sectionVariant: "split",
      closingVariant: "qa",
    },
  },
  {
    id: "mustard-zine",
    name: "Mustard Zine",
    tagline: "Mustard and ink with serif type. Zine-style storytelling.",
    category: "Editorial",
    themeId: "mustard",
    fontId: "fraunces",
    graphicId: "ribbon-stripe",
    density: "detailed",
    includeReferences: false,
    samplePrompt: "Field journal of a year-long product research project. The questions, what we found, what surprised us.",
    variants: {
      titleVariant: "numbered", bulletsVariant: "dashed", twoColumnVariant: "divider",
      tableVariant: "minimal", quoteVariant: "editorial", sectionVariant: "chapter",
      closingVariant: "signature",
    },
  },
  {
    id: "coral-pop",
    name: "Coral Pop",
    tagline: "Solid coral with charcoal accents. Energetic launches.",
    category: "Marketing",
    themeId: "coral-solid",
    fontId: "syne",
    graphicId: "corner-blocks",
    density: "concise",
    includeReferences: false,
    samplePrompt: "Product launch deck: the problem, the leap, the ask, the timeline.",
    variants: {
      titleVariant: "big-initial", bulletsVariant: "cards", twoColumnVariant: "cards",
      tableVariant: "accent-header", quoteVariant: "stacked", sectionVariant: "kicker-hero",
      closingVariant: "cta",
    },
  },
  {
    id: "clay-warm",
    name: "Clay & Cream",
    tagline: "Earthy clay with cream. Hospitality, food, lifestyle.",
    category: "Brand",
    themeId: "clay-cream",
    fontId: "lora",
    graphicId: "minimal-divider",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Restaurant concept deck: the cuisine, the room, the menu, the team, the build.",
    variants: {
      titleVariant: "centered", bulletsVariant: "dashed", twoColumnVariant: "divider",
      tableVariant: "minimal", quoteVariant: "editorial", sectionVariant: "minimal",
      closingVariant: "signature",
    },
  },
  {
    id: "quiet-blue",
    name: "Quiet Blue",
    tagline: "Subtle slate-blue. Polished internal updates.",
    category: "Investor",
    themeId: "quiet-blue",
    fontId: "inter",
    graphicId: "side-bar",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Monthly business review: revenue, retention, hiring, what shipped, what's next.",
    variants: {
      titleVariant: "underlined", bulletsVariant: "numbered", twoColumnVariant: "numbered",
      tableVariant: "accent-header", quoteVariant: "card", sectionVariant: "minimal",
      closingVariant: "contact",
    },
  },
  {
    id: "stripe-fashion",
    name: "Editorial Stripe",
    tagline: "Burgundy stripe, magazine pacing. Fashion lookbooks and runway notes.",
    category: "Editorial",
    themeId: "burgundy",
    fontId: "playfair",
    graphicId: "minimal-divider",
    density: "detailed",
    includeReferences: false,
    samplePrompt: "Lookbook walkthrough for a fall collection. Inspiration, silhouettes, palette, the show.",
    variants: {
      titleVariant: "underlined", bulletsVariant: "dashed", twoColumnVariant: "divider",
      tableVariant: "minimal", quoteVariant: "editorial", sectionVariant: "kicker-hero",
      closingVariant: "signature",
    },
  },
  {
    id: "indigo-enterprise",
    name: "Indigo Enterprise",
    tagline: "Royal indigo, generous spacing. Enterprise sales decks.",
    category: "Sales",
    themeId: "royal-indigo",
    fontId: "ibm-plex-sans",
    graphicId: "side-bar",
    density: "detailed",
    includeReferences: false,
    samplePrompt: "Enterprise sales pitch for our security platform. Risks, our approach, deployment, references.",
    variants: {
      titleVariant: "asymmetric", bulletsVariant: "icon-check", twoColumnVariant: "numbered",
      tableVariant: "accent-header", quoteVariant: "card", sectionVariant: "split",
      closingVariant: "contact",
    },
  },
  {
    id: "split-bold",
    name: "Split Bold",
    tagline: "Diagonal split, big numbers. Performance recaps.",
    category: "Strategy",
    themeId: "charcoal",
    fontId: "bricolage",
    graphicId: "split-diagonal",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Year-end recap. The numbers, the wins, the misses, what we learned, the next chapter.",
    variants: {
      titleVariant: "numbered", bulletsVariant: "numbered", twoColumnVariant: "compare",
      tableVariant: "accent-header", quoteVariant: "stacked", sectionVariant: "chapter",
      closingVariant: "signature",
    },
  },
  {
    id: "minimal-mono",
    name: "Minimal Mono",
    tagline: "All-mono type, ultra-minimal. Code reviews and post-mortems.",
    category: "Engineering",
    themeId: "ivory",
    fontId: "jetbrains",
    graphicId: "minimal-divider",
    density: "comprehensive",
    includeReferences: false,
    samplePrompt: "Incident post-mortem: timeline, root cause, contributing factors, action items.",
    variants: {
      titleVariant: "underlined", bulletsVariant: "dashed", twoColumnVariant: "classic",
      tableVariant: "minimal", quoteVariant: "card", sectionVariant: "minimal",
      closingVariant: "centered",
    },
  },
  {
    id: "purple-keynote",
    name: "Purple Keynote",
    tagline: "Bold purple, silver accents. Conference keynotes.",
    category: "Keynote",
    themeId: "purple-white",
    fontId: "outfit",
    graphicId: "concentric",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Conference keynote on the future of work. The shift, the data, the new social contract.",
    variants: {
      titleVariant: "big-initial", bulletsVariant: "cards", twoColumnVariant: "cards",
      tableVariant: "accent-header", quoteVariant: "stacked", sectionVariant: "kicker-hero",
      closingVariant: "cta",
    },
  },
  {
    id: "teal-pro",
    name: "Teal Professional",
    tagline: "Teal accents, crisp text. Healthcare and SaaS.",
    category: "Investor",
    themeId: "teal-white",
    fontId: "manrope",
    graphicId: "wave",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Series A pitch for a digital health platform. The problem, the model, traction, the team.",
    variants: {
      titleVariant: "asymmetric", bulletsVariant: "numbered", twoColumnVariant: "numbered",
      tableVariant: "accent-header", quoteVariant: "card", sectionVariant: "split",
      closingVariant: "contact",
    },
  },
  {
    id: "fog-product",
    name: "Fog Product",
    tagline: "Cool fog grays. Modern product reviews.",
    category: "Engineering",
    themeId: "fog",
    fontId: "plus-jakarta",
    graphicId: "soft-grid",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Quarterly product review. What we shipped, what users said, what's next on the roadmap.",
    variants: {
      titleVariant: "underlined", bulletsVariant: "icon-check", twoColumnVariant: "compare",
      tableVariant: "zebra", quoteVariant: "card", sectionVariant: "minimal",
      closingVariant: "qa",
    },
  },
  {
    id: "slate-coral",
    name: "Slate & Coral",
    tagline: "Slate with coral pop. Brand strategy and creative pitches.",
    category: "Brand",
    themeId: "slate-coral",
    fontId: "outfit",
    graphicId: "corner-circles",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Brand strategy proposal. Positioning, voice, identity, the rollout.",
    variants: {
      titleVariant: "centered", bulletsVariant: "cards", twoColumnVariant: "cards",
      tableVariant: "minimal", quoteVariant: "stacked", sectionVariant: "kicker-hero",
      closingVariant: "cta",
    },
  },
  {
    id: "charcoal-mono",
    name: "Charcoal Mono",
    tagline: "Charcoal with single-color discipline. Premium product launches.",
    category: "Keynote",
    themeId: "charcoal",
    fontId: "space-grotesk",
    graphicId: "concentric",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Launch deck for our flagship product. The moment, the why, the demo, the rollout.",
    variants: {
      titleVariant: "big-initial", bulletsVariant: "numbered", twoColumnVariant: "compare",
      tableVariant: "accent-header", quoteVariant: "stacked", sectionVariant: "split",
      closingVariant: "cta",
    },
  },
  {
    id: "green-academic",
    name: "Green Academic",
    tagline: "Forest green serif. Lectures, theses, journal-style decks.",
    category: "Lecture",
    themeId: "green-white",
    fontId: "merriweather",
    graphicId: "minimal-divider",
    density: "comprehensive",
    includeReferences: true,
    samplePrompt: "Graduate thesis defense: motivation, related work, contributions, evaluation, future directions.",
    variants: {
      titleVariant: "centered", bulletsVariant: "dashed", twoColumnVariant: "divider",
      tableVariant: "minimal", quoteVariant: "card", sectionVariant: "chapter",
      closingVariant: "qa",
    },
  },
  {
    id: "tangerine-event",
    name: "Tangerine Event",
    tagline: "High-energy tangerine. Event programs and festival decks.",
    category: "Marketing",
    themeId: "tangerine",
    fontId: "syne",
    graphicId: "ribbon-stripe",
    density: "concise",
    includeReferences: false,
    samplePrompt: "Festival program: the lineup, the venues, the schedule, sponsors, how to get there.",
    variants: {
      titleVariant: "big-initial", bulletsVariant: "cards", twoColumnVariant: "cards",
      tableVariant: "accent-header", quoteVariant: "stacked", sectionVariant: "kicker-hero",
      closingVariant: "cta",
    },
  },
  {
    id: "mint-friendly",
    name: "Mint Friendly",
    tagline: "Bright mint accents. HR, culture, internal communications.",
    category: "Training",
    themeId: "mint-sage",
    fontId: "figtree",
    graphicId: "dot-field",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "All-hands culture deck. Our values, behaviors we celebrate, how decisions get made.",
    variants: {
      titleVariant: "centered", bulletsVariant: "icon-check", twoColumnVariant: "cards",
      tableVariant: "minimal", quoteVariant: "card", sectionVariant: "kicker-hero",
      closingVariant: "qa",
    },
  },
];

/** Apply template variant defaults to a slide. Slide-level fields win, so
 *  AI-generated kicker/title/etc remain. The template only fills in
 *  variant slots that the slide hasn't already set. */
export function applyTemplateToSlide(slide: Slide, t: TemplateVariantDefaults): Slide {
  return {
    ...slide,
    titleVariant:    slide.titleVariant    ?? t.titleVariant,
    bulletsVariant:  slide.bulletsVariant  ?? t.bulletsVariant,
    twoColumnVariant:slide.twoColumnVariant?? t.twoColumnVariant,
    tableVariant:    slide.tableVariant    ?? t.tableVariant,
    quoteVariant:    slide.quoteVariant    ?? t.quoteVariant,
    sectionVariant:  slide.sectionVariant  ?? t.sectionVariant,
    closingVariant:  slide.closingVariant  ?? t.closingVariant,
  };
}

export function getTemplate(id?: string): DeckTemplate | undefined {
  return DECK_TEMPLATES.find((t) => t.id === id);
}
